name: Linnet
configs:
  Debug: debug
  Release: release
options:
  bundleIdPrefix: com.linnet
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
settings:
  base:
    SWIFT_VERSION: "6.0"
targets:
  Linnet:
    type: application
    platform: macOS
    sources:
      - path: Linnet
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.linnet.app
        PRODUCT_NAME: Linnet
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.music"
        CODE_SIGN_ENTITLEMENTS: Linnet/Linnet.entitlements
        CODE_SIGN_IDENTITY: "Apple Development"
        DEVELOPMENT_TEAM: "${DEVELOPMENT_TEAM}"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
      configs:
        Release:
          CODE_SIGN_IDENTITY: "Apple Distribution"
          ENABLE_TESTFLIGHT_INTERNAL_TESTING: "YES"
    dependencies:
      - package: LinnetAudio
      - package: LinnetLibrary
      - package: LinnetAI
packages:
  LinnetAudio:
    path: Packages/LinnetAudio
  LinnetLibrary:
    path: Packages/LinnetLibrary
  LinnetAI:
    path: Packages/LinnetAI
